### PR TITLE
Go to sleep tag

### PR DESCRIPTION
**Pull request by i509VCB**
Does what it says on the tin

### CODE REVIEW

**Review by Arc-blroth — APPROVED** [review]
I am slightly concerned by the use of profanity in an official community tag, but looks good otherwise 👍

**Review by gdude2002 — CHANGES_REQUESTED** [review]
Can't do substitutions outside the embed body, and it would be best to avoid swearing imo

**Comment by gdude2002** [comment]
Also, we've had problems with tags that target specific people being spammed a lot, so maybe this isn't a great idea

**Review by gdude2002 — COMMENTED** [review]
I am still concerned that a user-targetted tag might be a problem, like `??bean` was, but I need to bed myself now so I'll look at it tomorrow

image

**Review by YTG1234 — APPROVED** [review]

**Review by user11681 — APPROVED** [review]
:rocket:

**Comment by i509VCB** [comment]
Yeah nah

**Pull request closed without merging**
