### PR TITLE
Tag with link to a list of ports from Forge

### PR DESCRIPTION
**Pull request by TrueCP6**
This gist could help users who have recently moved to Fabric from Forge find mods to use they are familiar with so that they can get started with Fabric quicker.

### CODE REVIEW

**Comment by i509VCB** [comment]
I have no issue with this myself but the gist doesn't really say what each mod is a replacement for and is rather just a list of mods.

**Comment by TrueCP6** [comment]
The gist is a list of Forge mods with links to their Fabric counterparts.

**Review by user11681 — APPROVED** [review]

**Comment by i509VCB** [comment]
If you could explain the structure of name -> replacement mod at the top of the gist I have no issues here with merging this.

Reason being someone may not know that clicking the forge mod name will put them to an alternative.

**Comment by TrueCP6** [comment]
I have added a short description to the top of the gist.

**Review by i509VCB — APPROVED** [review]
This is fine now

**Comment by liach** [comment]
I really dislike this as this renders fabric as some peripheral mod loader on forge. We aren't.

**Pull request merged**
