### PR TITLE
Add curseforgemod and mr tags

### PR DESCRIPTION
**Pull request by Leo40Git**
- `curseforgemod` => `cf`
- `modrinthmod` => `mr`

OCD change.

### CODE REVIEW

**Comment by gdude2002** [comment]
We're not quite ready for PRs yet, give us some time to get the GH action in please

**Review by YTG1234 — APPROVED** [review]

**Comment by gdude2002** [comment]
I know this is nitpicky, but I think I'd prefer `mr` to be the main tag and `modrinthmod` to be the alias. Gotta keep things consistent.

**Comment by Leo40Git** [comment]
Done.

**Comment by gdude2002** [comment]
:+1:

**Pull request merged**
