### PR TITLE
Begin removal of 3rd party links no longer specific to Fabric

### PR DESCRIPTION
**Pull request by PseudoDistant**
I have created my own forks of 

https://github.com/LambdAurora/optifine_alternatives

https://github.com/comp500/quilt-serverside-mods

and I replaced the links to these with my own.

(Also I restored the Legacy Fabric invite link.)

### CODE REVIEW

**Comment by Technici4n** [comment]
I don't think this makes sense. Both links are actively maintained, have a trustworthy history, and contain accurate information.

We could maybe add a note next to the link to https://github.com/comp500/quilt-serverside-mods saying that most of the list is Fabric mods that can be used on Fabric. The idea would be to reduce user confusion. I don't see anything else that needs to be done.

**Comment by sfPlayer1** [comment]
These should be moved to the wiki, where any interested party can contribute.

**Comment by PseudoDistant** [comment]
They have been moved to the wiki.

And now I shall go on to do wiki things wikily.

**Review by sfPlayer1 — APPROVED** [review]

**Comment by LambdAurora** [comment]
I am not sure to see how https://github.com/LambdAurora/optifine_alternatives is hostile?
I guess the only hostility it has is against OptiFine, but your fork doesn't solve that either :P

I also would like to point out that those two are GitHub repositories with the interest of allowing people to contribute too.
I just would like to point out that for the OF alternatives the wiki won't be able to be as thorough as the repo due to the limitations of the format.

**Pull request merged**
