### PR TITLE
Update jdk.ytag

### PR DESCRIPTION
**Pull request by Yoosk**
AdoptOpenJDK is moving to the Eclipse Foundation and rebranding.
July 2021 and future releases will come from Adoptium.net

### CODE REVIEW

**Comment by modmuss50** [comment]
Would it be better to point users in the direction of Microsoft’s versions? I have seen a few users unsure if the adopt open jdk builds are legit due to the lesser know source.

I’d be interested to see what other people think?

**Comment by NinjaPhenix** [comment]
Sounds like Microsoft's JDK builds are using Adoptium's as a base: <https://www.microsoft.com/openjdk>, however since Microsoft does have Java 16 builds released now it may be wise to promote them as they are likely the builds Mojang are using.

**Comment by Yoosk** [comment]
True that, i was used to AdoptOpenJDK ones but it might be better to go with Microsoft as it is really known by your average user.

**Comment by intact** [comment]
Adoptium.net page is simple to use

**Comment by liach** [comment]
The jdk mojang ships is oracle jdk (can be confirmed by typing `java -version` and it shows `Java (TM)`, and it ships javac); I would recommend using the oracle jdk directly for better compatibility or use the base openjdk from openjdk.java.net than those from other sources.

**Comment by UpcraftLP** [comment]
> The jdk mojang ships is oracle jdk

That's only true for java 8. The java 16 JDK is by Microsoft.
```
 C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin> ./java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Microsoft-22300 (build 16.0.1+9)
OpenJDK 64-Bit Server VM Microsoft-22300 (build 16.0.1+9, mixed mode)
```

**Comment by modmuss50** [comment]
I will merge this for now, we can look at moving to MS's another time.

**Pull request merged**
