### PR TITLE
Add API's

### PR DESCRIPTION
**Pull request by OverlordsIII**
Adds api's from [the wiki](https://fabricmc.net/wiki/documentation:libraries) into tags. Note: EnergonRelics API could not make the list due to the author's jenkins being down.

### CODE REVIEW

**Review by YTG1234 — CHANGES_REQUESTED** [review]
Maybe you could add a short description of what the API does into each tag?

**Comment by OverlordsIII** [comment]
> Maybe you could add a short description of what the API does into each tag?

Ok I'll add it. It will take a little bit though

**Comment by OverlordsIII** [comment]
Also looks like [the link for FreshCoffee](https://gitea.thebrokenrail.com/TheBrokenRail/FreshCoffee.git) seems to be broken as well

**Comment by OverlordsIII** [comment]
Ok I've added descriptions to all the tags in the lib section

**Comment by Scotsguy** [comment]
Oh I love it, thank you.
BrokenRail's gitea seems to work again, just a bit unstable

**Comment by OverlordsIII** [comment]
Ok I'll add it back

**Review by gdude2002 — CHANGES_REQUESTED** [review]
Some of these files do not end with a newline - please do that. Otherwise, I think we're probably good.

**Review by gdude2002 — APPROVED** [review]

**Pull request merged**
